# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bits, Bytes, and Gates
email: matt.ballance@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  There's oh so much fun to be had. At the leading edge, 
  at the bleeding edge, at the confluence of bits, bytes, and gates.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitsbytesgates.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
subscribe_url: https://docs.google.com/forms/d/e/1FAIpQLSeGDpQMtOqutWiLVXcR84rMQV5hzkYbPVlhx23KxEN8NMnsXA/formResponse
subscribe_id: entry.9235671

#<form action="
#https://docs.google.com/forms/u/0/d/e/1FAIpQLSeGDpQMtOqutWiLVXcR84rMQV5hzkYbPVlhx23KxEN8NMnsXA/formResponse
#" target="_self" method="POST" id="mG61Hd" jsmodel="TOfxwf Q91hve CEkLOc" data-shuffle-seed="7577375473951449778" data-response="%.@.[]]" data-dlp-data="%.@.null,false,[]]" data-first-entry="0" data-last-entry="1" data-is-first-page="true"><div jscontroller="yUS4Lc" jsaction="rcuQ6b:rcuQ6b;UxRBlf:rcuQ6b;"><div jsname="o6bZLc"><input type="hidden" name="entry.9235671" value=""></div></div><div class="RH5hzf RLS9Fe"><div class="lrKTG"><div class="Dq4amc"><div class="m7w29c O8VmIc tIvQIf"><noscript><div class="HB1eCd-X3SwIb-haAclf"><div class="HB1eCd-X3SwIb-i8xkGf"><div class="tk3N6e-cXJiPb tk3N6e-cXJiPb-TSZdd tk3N6e-cXJiPb-GMvhG">JavaScript isn't enabled in your browser, so this file can't be opened. Enable and reload.</div></div><br></div></noscript><div class="JH79cc RVEQke b33AEc"></div><div class="N0gd6"><div class="ahS2Le"><div class="F9yp7e ikZYwf LgNcQe" dir="auto" role="heading" aria-level="1">Subscribe</div></div><div class="cBGGJ OIC90c" dir="auto">Subscribe to Bits, Bytes, and Gates</div><div jsname="F0H8Yc" class="liS6Hc"></div></div><div class="zAVwcb"></div><div class="DqBBlb"><div class="Oh1Vtf"><div class="tMRmsd" id="wSDd7b"><div class="ut7aeb"><div class="eAQI0e"><span class="EbMsme">bitsbytesgates.blog@gmail.com</span> <a href="https://accounts.google.com/AccountChooser?continue=https://docs.google.com/forms/d/e/1FAIpQLSeGDpQMtOqutWiLVXcR84rMQV5hzkYbPVlhx23KxEN8NMnsXA/viewform&amp;service=wise" aria-describedby="wSDd7b" class="jZZ5Nd">Switch account</a></div></div><div class="ut7aeb KA8vlc"><div jscontroller="By0w6" jsaction="mouseover:eGiyHb; click:eGiyHb; focus:eGiyHb; touchstart:eGiyHb;" data-tooltip="Your email and Google account are not part of your response" aria-label="Your email and Google account are not part of your response" role="img" tabindex="0"><div class="Axnmtb"><div class="foqfDc gdyQ3c"><div class="Y0xAIe BNL9Bd NpcyEe-n5T17d-Bz112c-xvr5H-lcE6r-JLm1tf-vTZmwf-BvMwwf" aria-hidden="true">&nbsp;</div><div class="Y0xAIe ivmiLb NpcyEe-n5T17d-Bz112c-xvr5H-lcE6r-JLm1tf-vTZmwf-AhqUyc" aria-hidden="true">&nbsp;</div><div class="Y0xAIe tDDvMb NpcyEe-n5T17d-Bz112c-xvr5H-lcE6r-JLm1tf-vTZmwf" aria-hidden="true">&nbsp;</div></div></div></div><div class="Q99PAd">Not shared</div></div></div><div class="UpwdYb" jscontroller="rmdjlf" jsaction="rcuQ6b:npT2md; click:xdDXgc;"><div class="foqfDc gdyQ3c"><div class="Y0xAIe BNL9Bd NpcyEe-n5T17d-Bz112c-DcLNVc-iib5kc-BvMwwf" aria-hidden="true">&nbsp;</div><div class="Y0xAIe ivmiLb NpcyEe-n5T17d-Bz112c-DcLNVc-iib5kc-AhqUyc" aria-hidden="true">&nbsp;</div><div class="Y0xAIe tDDvMb NpcyEe-n5T17d-Bz112c-DcLNVc-iib5kc" aria-hidden="true">&nbsp;</div></div></div></div><div class="zAVwcb"></div><div class="md0UAd" aria-hidden="true" dir="auto">* Indicates required question</div></div></div></div><div class="o3Dpx" role="list"><div class="Qr7Oae" role="listitem"><div jsmodel="CP1oW" data-params="%.@.[1689896314,&quot;Email:&quot;,null,0,[[9235671,[],true,[],[[2,102,[]]],null,null,null,null,null,[null,[]]]],null,null,null,[],null,null,[null,&quot;Email:&quot;]],&quot;i1&quot;,&quot;i2&quot;,&quot;i3&quot;,false]"><div jscontroller="sWGJ4b" jsaction="EEvAHc:yfX9oc;" jsname="WsjYwc" class="geS5n"><div class="z12JJ"><div class="M4DNQ"><div id="i1" class="HoXoMd D1wxyf RjsPE" role="heading" aria-level="3" aria-describedby="i4"><span class="M7eMe">Email:</span><span class="vnumgf" id="i4" aria-label="Required question"> *</span></div><div class="gubaDc OIC90c RjsPE" id="i2"></div></div></div><div jscontroller="oCiKKc" jsaction="rcuQ6b:vZc4S;O22p3e:zjh6rb;b2trFe:eVidQc;sPvj8e:d3sQLd;AHmuwe:h06R8;" class="AgroKb"><div class="rFrNMe k3kHxc RdH0ib yqQS1 Z02LAf zKHdkd" jscontroller="pxq3x" jsaction="clickonly:KjsqPd; focus:Jt1EX; blur:fpfTEe; input:Lg5SV" jsshadow="" jsname="YPqjbf"><div class="aCsJod oJeWuf"><div class="aXBtI Wic03c"><div class="Xb9hP"><input type="email" class="whsOnd zHQkBf" jsname="YPqjbf" autocomplete="off" tabindex="0" aria-labelledby="i1" aria-describedby="i2 i3" required="" dir="auto" data-initial-dir="auto" data-initial-value=""><div jsname="LwH6nd" class="ndJi5d snByac" aria-hidden="true">Your answer</div></div><div class="i9lrp mIZh1c"></div><div jsname="XmnwAc" class="OabDMe cXrdqd"></div></div></div><div class="LXRPh"><div jsname="ty6ygf" class="ovnfwe Is7Fhb"></div></div></div></div><div jsname="Rfh2Tc" class="SL4Sz" id="i3" role="alert"></div></div></div></div></div><div class="ThHDze" jscontroller="lSvzH" jsaction="rcuQ6b:npT2md;JIbuQc:qV61Ff(X5DuWc),Gl574d(QR6bsb),V3upec(GeGHKb),HiUbje(M2UYVd),NPBnCf(OCpkoe); keydown:duASZc" data-shuffle-seed="7577375473951449778" data-should-execute-invisible-captcha-challenge="false" data-is-receipt-checked="false"><div class="DE3NNc CekdCb"><div class="lRwqcd"><div role="button" class="uArJ5e UQuaGc Y5sE8d VkkpIf QvWxOd" jscontroller="VXdfxd" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; mouseenter:tfO1Yc; mouseleave:JywGue;touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc(preventMouseEvents=true|preventDefault=true); touchcancel:JMtRjd;focus:AHmuwe; blur:O22p3e; contextmenu:mg9Pef;" jsshadow="" jsname="M2UYVd" tabindex="0"><div class="Fvio9d MbhUzd" jsname="ksKsZd"></div><div class="e19J0b CeoRYc"></div><span jsslot="" class="l4V7wb Fxmcue"><span class="NPEfkd RveJvd snByac">Submit</span></span></div></div><div class="nYdzXd"><div role="button" class="uArJ5e UQuaGc kCyAyd l3F1ye TFBnVe" jscontroller="VXdfxd" jsaction="click:cOuCgd; mousedown:UX7yZ; mouseup:lbsD7e; mouseenter:tfO1Yc; mouseleave:JywGue;touchstart:p6p2H; touchmove:FwuNnf; touchend:yfqBxc(preventMouseEvents=true|preventDefault=true); touchcancel:JMtRjd;focus:AHmuwe; blur:O22p3e; contextmenu:mg9Pef;" jsshadow="" jsname="X5DuWc" tabindex="0"><div class="Fvio9d MbhUzd" jsname="ksKsZd"></div><div class="e19J0b CeoRYc"></div><span jsslot="" class="l4V7wb Fxmcue"><span class="NPEfkd RveJvd snByac">Clear form</span></span></div></div></div><div class="T2dutf">Never submit passwords through Google Forms.</div></div><input type="hidden" name="fvv" value="1"><input type="hidden" name="partialResponse" value="[null,null,&quot;7577375473951449778&quot;]"><input type="hidden" name="pageHistory" value="0"><input type="hidden" name="fbzx" value="7577375473951449778"></div></div></form>

#markdown: kramdown

#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-mermaid

highlighter: rouge

# The mermaid plug-in expects a .js to include above each diagram. We take
# care of loading elsewhere, so this is just a stub to keep the plug-in happy
mermaid:
  src: "public/js/stub.js"
#  src: "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs"

include:
  - _series/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
