name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1
        - name: Install Tools
          run: |
            sudo apt-get install ruby-full python3 bundler build-essential zlib1g-dev ninja-build
        - name: Install IVPM
          run: |
            python3 -m pip install ivpm
        - name: Install Dependencies
          run: |
            python3 -m ivpm update -a
            bundle config set path vendor
            bundle install
        - name: Install and build
          run: |
            export JEKYLL_ENV=production
            bundle exec jekyll build -d web
            touch web/.nojekyll

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: gh-pages # The branch the action should deploy to.
            folder: web # The folder the action should deploy.

